name: runs demo

on: [watch]

jobs:
  demo-me:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout code
      uses: actions/checkout@v2
    - name: docker build
      run: docker build -t some-image:v1 ${{ github.WORKSPACE }}/Dockerfile
    
